# Usamos una versión ligera de Python 3.12
FROM python:3.12-slim

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos SOLO el archivo de requerimientos primero
# Esto ayuda a que Docker guarde en caché las instalaciones de pip y sea más rápido
COPY requirements.txt .

# Instalamos las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Ahora copiamos todo el resto del código de la carpeta flask al contenedor
COPY . .

# Exponemos el puerto interno 5000 (el que configuramos en el docker-compose.yml)
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]